// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SkillProcess, SkillProcessData } from "./tables/SkillProcess.sol";
import { SkillPrcMtrlCount } from "./tables/SkillPrcMtrlCount.sol";
import { SkillPrcMtrl, SkillPrcMtrlData } from "./tables/SkillPrcMtrl.sol";
import { Counter } from "./tables/Counter.sol";
