// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISkillProcessSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISkillProcessSystem {
  function app__createSkillProcess(
    uint8 skillType,
    uint256 playerId,
    uint32 itemId,
    uint32 batchSize
  ) external returns (uint8);
}
